#!/usr/bin/env python3
"""pattern_gen_hybrid.py

Hybrid RIS phase pattern generator (steering + focusing) with automatic mode selection.

Usage: run as a script. Edit parameters in the `if __name__ == "__main__":` block
or import functions programmatically.

Outputs:
 - RIS_phase_pattern_hybrid.png
 - Optional CSV files when export_csv=True

Author: Generated by assistant
"""

import numpy as np
import matplotlib.pyplot as plt
import math
import os

# --------------------------
# Physical constants & defaults
# --------------------------
c = 299_792_458.0

def generate_ris_grid(N, d):
    """Return x_rel, y_rel meshgrids (shape N×N) centered at 0."""
    lim_x = (N - 1) / 2 * d
    lim_y = (N - 1) / 2 * d
    x_coords = np.linspace(-lim_x, lim_x, N)
    y_coords = np.linspace(-lim_y, lim_y, N)
    X, Y = np.meshgrid(x_coords, y_coords)
    Z = np.zeros_like(X)
    return X, Y, Z

def incident_phase(k, source, ris_center, x_rel, y_rel):
    """Compute spherical incident phase from source to each RIS element."""
    delta_x_s = source[0] - ris_center[0]
    delta_y_s = source[1] - ris_center[1]
    delta_z_s = source[2] - ris_center[2]
    r_src = np.sqrt((delta_x_s - x_rel)**2 + (delta_y_s - y_rel)**2 + (delta_z_s)**2)
    return k * r_src, r_src

def steering_phase(k, ris_center, target, x_rel, y_rel):
    """Compute azimuth+elevation steering linear-phase component."""
    # Direction vector from RIS center to target
    v_out = np.array([target[0] - ris_center[0], target[1] - ris_center[1], target[2] - ris_center[2]])
    norm = np.linalg.norm(v_out)
    if norm == 0:
        # degenerate: target at RIS center -> no steering
        return np.zeros_like(x_rel), 0.0, 0.0
    v_hat = v_out / norm
    # Azimuth and elevation
    theta_az = math.atan2(v_out[1], v_out[0])           # radians
    # elevation defined by angle between horizontal plane and vector
    theta_el = math.asin(v_hat[2])                      # radians, in [-pi/2, pi/2]
    # Linear-phase approximation: phi_steer = -k * (x*sin(az_comp) + y*sin(el_comp))
    # We follow formula.md convention: use sin(theta_az) and sin(theta_el)
    phi_steer = -k * (x_rel * math.sin(theta_az) + y_rel * math.sin(theta_el))
    return phi_steer, theta_az, theta_el

def focusing_phase(k, target, ris_center, x_rel, y_rel, z_rel):
    """Compute spherical focusing phase from each RIS element to target."""
    x_abs = ris_center[0] + x_rel
    y_abs = ris_center[1] + y_rel
    z_abs = ris_center[2] + z_rel
    r_rcv = np.sqrt((target[0] - x_abs)**2 + (target[1] - y_abs)**2 + (target[2] - z_abs)**2)
    return k * r_rcv, r_rcv

def quantize_phase_deg(phase_rad, n_bit):
    """Quantize phase (radians) to n_bit levels and return degrees matrix."""
    phase_deg = np.degrees(phase_rad) % 360.0
    L = 2 ** n_bit
    if L <= 1:
        return phase_deg, phase_deg  # no quantization
    # Map to 0..L-1 then back to degrees using (L-1) steps (same as formula.md)
    levels = np.round((phase_deg / 360.0) * (L - 1))
    phase_q_deg = (levels / (L - 1)) * 360.0
    return phase_q_deg, phase_deg

def fraunhofer_boundary(N, d, wavelength):
    """Compute approximate Fraunhofer boundary r_boundary = 2 D^2 / lambda\n    where D is approximate aperture (N-1)*d.\n    """
    D = (N - 1) * d
    return 2.0 * (D ** 2) / wavelength

def generate_phase_map(f, source, ris_center, target, N=16, n_bit=1, mode='auto', export_csv=False, plot_components=False):
    """Generate hybrid RIS phase map and produce plots/files.\n\n    mode: 'auto', 'steer', or 'focus'\n    """
    wavelength = c / f
    k = 2.0 * np.pi / wavelength
    d = wavelength / 2.0

    # grid
    x_rel, y_rel, z_rel = generate_ris_grid(N, d)

    # distances
    vec_in = source - ris_center
    vec_out = target - ris_center
    dist_ris_to_ue = np.linalg.norm(vec_out)

    # decide mode
    r_boundary = fraunhofer_boundary(N, d, wavelength)
    sel_mode = mode
    if mode == 'auto':
        sel_mode = 'steer' if dist_ris_to_ue > r_boundary else 'focus'

    # compute components
    phi_incident_rad, r_src = incident_phase(k, source, ris_center, x_rel, y_rel)

    if sel_mode == 'steer':
        phi_reflect_rad, az, el = steering_phase(k, ris_center, target, x_rel, y_rel)
        phi_total_rad = (phi_incident_rad + phi_reflect_rad) % (2.0 * np.pi)
        component_extra = ('steer', az, el)
    else:
        phi_reflect_rad, r_rcv = focusing_phase(k, target, ris_center, x_rel, y_rel, z_rel)
        phi_total_rad = (phi_incident_rad + phi_reflect_rad) % (2.0 * np.pi)
        component_extra = ('focus', r_rcv)

    # normalize
    phi_total_rad = np.where(phi_total_rad < 0, phi_total_rad + 2.0 * np.pi, phi_total_rad)

    # quantize
    phase_quant_deg, phase_deg = quantize_phase_deg(phi_total_rad, n_bit)

    # create output dict
    out = {
        'phi_incident_rad': phi_incident_rad,
        'phi_reflect_rad': phi_reflect_rad,
        'phi_total_rad': phi_total_rad,
        'phase_deg': phase_deg,
        'phase_quant_deg': phase_quant_deg,
        'mode': sel_mode,
        'r_boundary': r_boundary,
        'dist_ris_to_ue': dist_ris_to_ue,
        'component_extra': component_extra,
        'x_rel': x_rel,
        'y_rel': y_rel,
        'z_rel': z_rel,
        'wavelength': wavelength,
        'k': k,
        'd': d,
        'N': N,
    }

    # export CSV if requested
    if export_csv:
        base = 'RIS_phase_hybrid'
        np.savetxt(base + '_incident.csv', np.degrees(phi_incident_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_reflect.csv', np.degrees(phi_reflect_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_total_cont.csv', np.degrees(phi_total_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_quantized.csv', phase_quant_deg, fmt='%.1f', delimiter=',')

    # plotting
    plot_hybrid(out, source, ris_center, target, plot_components=plot_components)

    return out


def plot_hybrid(out, source, ris_center, target, plot_components=False):
    """Create and save figures for the hybrid RIS phase map."""
    phase_q = out['phase_quant_deg']
    phase_deg = out['phase_deg']
    N = out['N']
    n_bit = int(np.round(np.log2((360.0 / (360.0 / (2**1))) if False else 2)))  # placeholder not used

    # geometry elements
    AP = np.array([source[0], source[1]])
    RIS = np.array([ris_center[0], ris_center[1]])
    UE = np.array([target[0], target[1]])

    # compute some angle info for captions
    # If steering, include az/el; if focus, include mean focus distance
    mode = out['mode']
    r_boundary = out['r_boundary']
    dist_ris_to_ue = out['dist_ris_to_ue']

    title_extra = f"Mode: {mode.upper()} | RIS→UE distance: {dist_ris_to_ue:.2f} m | Fraunhofer boundary: {r_boundary:.2f} m"

    fig = plt.figure(figsize=(10, 14))
    gs = fig.add_gridspec(2, 2, height_ratios=[1.5, 1], width_ratios=[30, 1.2], hspace=0.35, wspace=0.08,
                          left=0.08, right=0.95, top=0.95, bottom=0.08)

    # Top: geometry
    ax_g = fig.add_subplot(gs[0, :])
    ax_g.scatter(AP[0], AP[1], s=120, color='green', marker='s', label='Source (AP)', zorder=5)
    ax_g.scatter(RIS[0], RIS[1], s=160, color='orange', marker='^', label='RIS', zorder=5)
    ax_g.scatter(UE[0], UE[1], s=120, color='red', marker='o', label='Target (UE)', zorder=5)
    ax_g.plot([RIS[0], AP[0]], [RIS[1], AP[1]], 'g--', lw=2, label='RIS↔AP', alpha=0.7)
    ax_g.plot([RIS[0], UE[0]], [RIS[1], UE[1]], 'r--', lw=2, label='RIS↔UE', alpha=0.7)
    ax_g.set_aspect('equal')
    ax_g.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
    ax_g.legend(loc='upper left', fontsize=10, framealpha=0.95, edgecolor='black')
    ax_g.set_title('RIS Geometry (Top-Down View) — Hybrid Steering/Focus', fontsize=14, fontweight='bold', pad=15)
    ax_g.set_xlabel('X (m)', fontsize=11)
    ax_g.set_ylabel('Y (m)', fontsize=11)

    # Bottom-left: phase heatmap
    ax_p = fig.add_subplot(gs[1, 0])
    num_levels = int(2 ** 1)
    vmax_phase = 360.0
    im = ax_p.imshow(phase_q, cmap='bwr', origin='lower', vmin=0, vmax=vmax_phase)
    ax_p.set_title('RIS Quantized Phase Map', fontsize=12, fontweight='bold')
    ax_p.set_xlabel('Element index (x)')
    ax_p.set_ylabel('Element index (y)')

    # Colorbar
    cax = fig.add_subplot(gs[1, 1])
    cbar = fig.colorbar(im, cax=cax)
    cbar.set_label('Quantized Phase (deg)')

    plt.savefig('RIS_phase_pattern_hybrid.png', dpi=150, bbox_inches='tight')
    print("Saved: RIS_phase_pattern_hybrid.png")
    plt.show()


if __name__ == '__main__':
    # Default example parameters (user can modify)
    f = 5.8e9
    source = np.array([8.0, 10.0, 0.5])
    ris_center = np.array([15.0, 10.0, 0.0])
    target = np.array([11.4, 6.5, 0.0])

    N = 16
    n_bit = 1
    mode = 'auto'           # 'auto', 'steer', or 'focus'
    export_csv = False
    plot_components = False

    out = generate_phase_map(f, source, ris_center, target, N=N, n_bit=n_bit, mode=mode,
                             export_csv=export_csv, plot_components=plot_components)

    print("Completed. Mode selected:", out['mode'])