#!/usr/bin/env python3
"""
pattern_gen_hybrid_with_arcs_patched.py

Patched hybrid RIS phase pattern generator with correct azimuth and elevation deflection arcs.
- Hybrid mode: 'steer', 'focus', 'auto' (automatic Fraunhofer selection)
- Geometry-derived deflection arcs always plotted (azimuth top-down, elevation side-view)
- Elevation arc implemented using a clean polar arc (constant arc radius) while AP/UE
  points remain at true horizontal ranges (hybrid visualization).

Outputs:
 - RIS_phase_pattern_hybrid_arcs.png
 - Optional CSV files when export_csv=True

Author: Generated by assistant (patched)
"""
import numpy as np
import matplotlib.pyplot as plt
import math
import os
from pathlib import Path

# --------------------------
# Physical constants & defaults
# --------------------------
c = 299_792_458.0

def generate_ris_grid(N, d):
    """Return x_rel, y_rel meshgrids (shape N×N) centered at 0."""
    lim_x = (N - 1) / 2 * d
    lim_y = (N - 1) / 2 * d
    x_coords = np.linspace(-lim_x, lim_x, N)
    y_coords = np.linspace(-lim_y, lim_y, N)
    X, Y = np.meshgrid(x_coords, y_coords)
    Z = np.zeros_like(X)
    return X, Y, Z

def incident_phase(k, source, ris_center, x_rel, y_rel, plane_tx=False):
    """Compute incident phase from source to each RIS element.

    Args:
        plane_tx: If True, use plane wave (far-field approximation).
                 If False, use spherical wave (near-field, default).
    """
    delta_x_s = source[0] - ris_center[0]
    delta_y_s = source[1] - ris_center[1]
    delta_z_s = source[2] - ris_center[2]

    if plane_tx:
        # Plane wave: linear phase gradient from direction vector
        norm_src = np.sqrt(delta_x_s**2 + delta_y_s**2 + delta_z_s**2)
        if norm_src < 1e-9:
            u_s_x, u_s_y = 0.0, 0.0
        else:
            u_s_x = delta_x_s / norm_src
            u_s_y = delta_y_s / norm_src
        phi_incident = -k * (x_rel * u_s_x + y_rel * u_s_y)
        return phi_incident, None
    else:
        # Spherical wave: distance-based phase
        r_src = np.sqrt((delta_x_s - x_rel)**2 + (delta_y_s - y_rel)**2 + (delta_z_s)**2)
        return k * r_src, r_src

def steering_phase(k, ris_center, target, x_rel, y_rel):
    """Compute azimuth+elevation steering linear-phase component."""
    # Direction vector from RIS center to target
    v_out = np.array([target[0] - ris_center[0], target[1] - ris_center[1], target[2] - ris_center[2]])
    norm = np.linalg.norm(v_out)
    if norm == 0:
        # degenerate: target at RIS center -> no steering
        return np.zeros_like(x_rel), 0.0, 0.0
    v_hat = v_out / norm
    # Azimuth and elevation
    theta_az = math.atan2(v_out[1], v_out[0])           # radians
    theta_el = math.asin(v_hat[2])                      # radians, in [-pi/2, pi/2]
    # Linear-phase approximation: phi_steer = -k * (x*sin(az_comp) + y*sin(el_comp))
    phi_steer = -k * (x_rel * math.sin(theta_az) + y_rel * math.sin(theta_el))
    return phi_steer, theta_az, theta_el

def focusing_phase(k, target, ris_center, x_rel, y_rel, z_rel):
    """Compute spherical focusing phase from each RIS element to target."""
    x_abs = ris_center[0] + x_rel
    y_abs = ris_center[1] + y_rel
    z_abs = ris_center[2] + z_rel
    r_rcv = np.sqrt((target[0] - x_abs)**2 + (target[1] - y_abs)**2 + (target[2] - z_abs)**2)
    return k * r_rcv, r_rcv

def quantize_phase_deg(phase_rad, n_bit):
    """Quantize phase (radians) to n_bit levels and return degrees matrix.
    Uses digitize method to match pattern_hybrid_sap.py quantization.
    """
    phase_deg = np.degrees(phase_rad) % 360.0
    L = 2 ** n_bit
    if L <= 1:
        return phase_deg, phase_deg  # no quantization

    # Quantize using digitize on radian intervals (0 to 2π)
    # Create interval boundaries in radians
    intervals = np.linspace(0, 2 * np.pi, L + 1, endpoint=True)
    levels = np.digitize(phase_rad, intervals) - 1

    # Convert levels back to phase degrees
    # Level k maps to (k / (L-1)) * 360 degrees
    phase_q_deg = (levels / (L - 1)) * 360.0

    return phase_q_deg, phase_deg

def fraunhofer_boundary(N, d, wavelength):
    """Compute approximate Fraunhofer boundary r_boundary = 2 D^2 / lambda
    where D is approximate aperture (N-1)*d.
    """
    D = (N - 1) * d
    return 2.0 * (D ** 2) / wavelength

def wrap_to_pi(angle):
    """Wrap angle (rad) to [-pi, +pi]."""
    a = (angle + np.pi) % (2 * np.pi) - np.pi
    return a

def generate_phase_map(f, source, ris_center, target, N=16, n_bit=1, mode='auto',
                       plane_tx=False, export_csv=False, plot_components=False):
    """Generate hybrid RIS phase map and produce plots/files.

    Args:
        mode: 'auto', 'steer', or 'focus'
        plane_tx: If True, use plane wave for TX (far-field). If False, spherical (near-field, default).
    """
    wavelength = c / f
    global k
    k = 2.0 * np.pi / wavelength
    d = wavelength / 2.0

    # grid
    x_rel, y_rel, z_rel = generate_ris_grid(N, d)

    # distances & vectors
    vec_in = source - ris_center      # AP -> RIS vector (from RIS center perspective)
    vec_out = target - ris_center    # UE -> RIS vector (from RIS center perspective)
    dist_ris_to_ue = np.linalg.norm(vec_out)

    # geometry angles (always computed)
    theta_in = math.atan2(source[1] - ris_center[1], source[0] - ris_center[0])
    theta_out = math.atan2(target[1] - ris_center[1], target[0] - ris_center[0])
    # wrap and deflection
    delta_theta = wrap_to_pi(theta_out - theta_in)
    azimuth_deflection = abs(delta_theta)

    # elevation angles (relative to horizontal)
    r_horizontal_source = math.hypot(source[0] - ris_center[0], source[1] - ris_center[1])
    r_horizontal_target = math.hypot(target[0] - ris_center[0], target[1] - ris_center[1])
    elevation_in = math.atan2(source[2] - ris_center[2], r_horizontal_source) if r_horizontal_source > 1e-9 else (math.copysign(math.pi/2, source[2]-ris_center[2]) if source[2]!=ris_center[2] else 0.0)
    elevation_out = math.atan2(target[2] - ris_center[2], r_horizontal_target) if r_horizontal_target > 1e-9 else (math.copysign(math.pi/2, target[2]-ris_center[2]) if target[2]!=ris_center[2] else 0.0)
    elevation_deflection = elevation_out - elevation_in

    # decide mode
    r_boundary = fraunhofer_boundary(N, d, wavelength)
    sel_mode = mode
    if mode == 'auto':
        sel_mode = 'steer' if dist_ris_to_ue > r_boundary else 'focus'

    # compute incident (TX phase)
    phi_incident_rad, r_src = incident_phase(k, source, ris_center, x_rel, y_rel, plane_tx=plane_tx)

    # compute reflect component based on selected mode
    if sel_mode == 'steer':
        phi_reflect_rad, az_used, el_used = steering_phase(k, ris_center, target, x_rel, y_rel)
    else:
        phi_reflect_rad, r_rcv = focusing_phase(k, target, ris_center, x_rel, y_rel, z_rel)

    # total
    phi_total_rad = (phi_incident_rad + phi_reflect_rad) % (2.0 * np.pi)
    phi_total_rad = np.where(phi_total_rad < 0, phi_total_rad + 2.0 * np.pi, phi_total_rad)

    # quantize
    phase_quant_deg, phase_deg = quantize_phase_deg(phi_total_rad, n_bit)

    out = {
        'phi_incident_rad': phi_incident_rad,
        'phi_reflect_rad': phi_reflect_rad,
        'phi_total_rad': phi_total_rad,
        'phase_deg': phase_deg,
        'phase_quant_deg': phase_quant_deg,
        'mode': sel_mode,
        'plane_tx': plane_tx,
        'r_boundary': r_boundary,
        'dist_ris_to_ue': dist_ris_to_ue,
        'azimuth_in_rad': theta_in,
        'azimuth_out_rad': theta_out,
        'azimuth_deflection_rad': azimuth_deflection,
        'elevation_in_rad': elevation_in,
        'elevation_out_rad': elevation_out,
        'elevation_deflection_rad': elevation_deflection,
        'x_rel': x_rel,
        'y_rel': y_rel,
        'z_rel': z_rel,
        'wavelength': wavelength,
        'k': k,
        'd': d,
        'N': N,
    }

    # export CSV if requested
    if export_csv:
        base = 'RIS_phase_hybrid'
        np.savetxt(base + '_incident.csv', np.degrees(phi_incident_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_reflect.csv', np.degrees(phi_reflect_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_total_cont.csv', np.degrees(phi_total_rad), fmt='%.2f', delimiter=',')
        np.savetxt(base + '_quantized.csv', phase_quant_deg, fmt='%.1f', delimiter=',')

    # plotting always includes arcs
    plot_hybrid_with_arcs(out, source, ris_center, target, plot_components=plot_components)

    return out

def plot_hybrid_with_arcs(out, source, ris_center, target, plot_components=False):
    """Create and save figures for the hybrid RIS phase map with azimuth + elevation arcs."""
    phase_q = out['phase_quant_deg']
    phase_deg = out['phase_deg']
    N = out['N']

    AP = np.array([source[0], source[1], source[2]])
    RIS = np.array([ris_center[0], ris_center[1], ris_center[2]])
    UE = np.array([target[0], target[1], target[2]])

    # Prepare figure with top-down and side-view panels
    fig = plt.figure(figsize=(14, 10))
    gs = fig.add_gridspec(3, 4, height_ratios=[1.2, 0.05, 1], width_ratios=[1, 1, 1, 0.4], hspace=0.35, wspace=0.4)

    # Top-down (XY) view — azimuth arc
    ax_xy = fig.add_subplot(gs[0, 0:2])
    ax_xy.scatter(AP[0], AP[1], s=120, color='green', marker='s', label='Source (AP)', zorder=5)
    ax_xy.scatter(RIS[0], RIS[1], s=160, color='orange', marker='^', label='RIS', zorder=5)
    ax_xy.scatter(UE[0], UE[1], s=120, color='red', marker='o', label='Target (UE)', zorder=5)
    ax_xy.plot([RIS[0], AP[0]], [RIS[1], AP[1]], 'g--', lw=2, label='RIS↔AP', alpha=0.7)
    ax_xy.plot([RIS[0], UE[0]], [RIS[1], UE[1]], 'r--', lw=2, label='RIS↔UE', alpha=0.7)

    # Azimuth arc: draw short arc from theta_in to theta_out around RIS center
    theta1 = out['azimuth_in_rad']
    theta2 = out['azimuth_out_rad']
    # ensure shortest direction for arc
    diff = wrap_to_pi(theta2 - theta1)
    npts = 200
    angles = theta1 + np.linspace(0, diff, npts)
    arc_r = max((np.linalg.norm(AP[:2]-RIS[:2]), np.linalg.norm(UE[:2]-RIS[:2]))) * 0.5 + 0.5
    xs = RIS[0] + arc_r * np.cos(angles)
    ys = RIS[1] + arc_r * np.sin(angles)
    ax_xy.plot(xs, ys, color='purple', lw=2.0, label=f'Azimuth deflection: {np.degrees(out["azimuth_deflection_rad"]):.2f}°')
    # label mid-angle
    mid_ang = theta1 + diff / 2.0
    ax_xy.text(RIS[0] + (arc_r+0.2) * np.cos(mid_ang), RIS[1] + (arc_r+0.2) * np.sin(mid_ang),
               f"{np.degrees(out['azimuth_deflection_rad']):.2f}°", color='purple', fontsize=10, fontweight='bold')

    ax_xy.set_aspect('equal')
    ax_xy.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
    ax_xy.legend(loc='upper left', fontsize=9)
    ax_xy.set_title('Top-Down View (XY) — Azimuth Deflection Arc')
    ax_xy.set_xlabel('X (m)')
    ax_xy.set_ylabel('Y (m)')

    # Side-view (range vs Z) — elevation arc
    ax_xz = fig.add_subplot(gs[0, 2])
    # compute horizontal ranges (true distances) for AP and UE relative to RIS center
    r_ap = math.hypot(AP[0]-RIS[0], AP[1]-RIS[1])
    r_ue = math.hypot(UE[0]-RIS[0], UE[1]-RIS[1])
    # plot AP and UE at their true horizontal ranges
    ax_xz.scatter([0, r_ap, r_ue], [RIS[2], AP[2], UE[2]], s=[160,120,120], color=['orange','green','red'], marker='o', zorder=5)
    ax_xz.plot([0, r_ap], [RIS[2], AP[2]], 'g--', lw=2, alpha=0.7)
    ax_xz.plot([0, r_ue], [RIS[2], UE[2]], 'r--', lw=2, alpha=0.7)

    # Elevation arc: hybrid style
    el1 = out['elevation_in_rad']
    el2 = out['elevation_out_rad']
    diff_el = el2 - el1
    npts_el = 200
    # choose an arc radius (in horizontal distance) that is visually meaningful but not overlapping points
    arc_r_el = max(r_ap, r_ue) * 0.5 + 0.6

    # Create polar-like arc centered at RIS: for angle theta in [el1, el2],
    # x_side = arc_r_el * cos(theta)  -> represents horizontal range along side-plot
    # z_side = RIS_z + arc_r_el * sin(theta) -> vertical position
    el_angles = el1 + np.linspace(0, diff_el, npts_el)
    ranges_arc = arc_r_el * np.cos(el_angles)   # relative horizontal offset from RIS (positive)
    zs_arc = RIS[2] + arc_r_el * np.sin(el_angles)

    # But the AP and UE actual ranges may not align with arc endpoints; plot arc within same axis
    ax_xz.plot(ranges_arc, zs_arc, color='teal', lw=2.2, label=f'Elevation deflection: {np.degrees(diff_el):.2f}°')
    # Label mid-point
    mid_el = el1 + diff_el / 2.0
    mid_range = arc_r_el * math.cos(mid_el)
    mid_z = RIS[2] + arc_r_el * math.sin(mid_el)
    ax_xz.text(mid_range, mid_z + 0.03, f"{np.degrees(diff_el):.2f}°", color='teal', fontsize=10, fontweight='bold')

    ax_xz.set_xlabel('Range from RIS center (m)')
    ax_xz.set_ylabel('Z (m)')
    ax_xz.set_title('Side View (Range vs Z) — Elevation Deflection Arc')
    ax_xz.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
    ax_xz.set_xlim(left=0)

    # Phase heatmap (bottom spanning columns)
    ax_phase = fig.add_subplot(gs[2, 0:3])
    im = ax_phase.imshow(phase_q, cmap='bwr', origin='lower')
    ax_phase.set_title(f'RIS Quantized Phase Map — Mode: {out["mode"].upper()}')
    ax_phase.set_xlabel('Element index (x)')
    ax_phase.set_ylabel('Element index (y)')
    # colorbar to the right
    cax = fig.add_subplot(gs[2, 3])
    cbar = fig.colorbar(im, cax=cax)
    cbar.set_label('Quantized Phase (deg)')

    plt.tight_layout()
    outpath = Path('RIS_phase_pattern_hybrid_arcs.png')
    plt.savefig(outpath, dpi=160, bbox_inches='tight')
    print(f"Saved: {outpath.resolve()}")
    plt.show()

if __name__ == '__main__':
    # Default parameters matching pattern_hybrid_sap.py
    # SAP spherical coords: r_src=0.5, theta_src=0°, phi_src=0°, r_rcv=0.5, theta_rcv=45°, phi_rcv=0°
    # Converted to Cartesian with RIS center at origin
    f = 5.8e9
    ris_center = np.array([0.0, 0.0, 0.0])
    source = np.array([0.0, 0.0, 0.5])          # AP directly above RIS (spherical: r=0.5, theta=0°, phi=0°)
    target = np.array([0.3536, 0.0, 0.3536])    # UE at 45° elevation (spherical: r=0.5, theta=45°, phi=0°)

    N = 16
    n_bit = 1
    mode = 'auto'           # 'auto', 'steer', or 'focus'
    plane_tx = False        # False: spherical TX (near-field, default), True: plane TX (far-field)
    export_csv = False
    plot_components = False

    out = generate_phase_map(f, source, ris_center, target, N=N, n_bit=n_bit, mode=mode,
                             plane_tx=plane_tx, export_csv=export_csv, plot_components=plot_components)

    print("Completed. Mode selected:", out['mode'])
