"""Channel model interfaces and compatibility adapters."""

from .base import ChannelEvaluation, ChannelModel
from .link_budget import (
    DEFAULT_RIS_LINK_CONFIG,
    LinkBudgetChannel,
    build_link_budget_config,
    build_link_budget_config_from_nodes,
    evaluate_ris_link_from_nodes,
    evaluate_ris_link_metrics,
)
from .simris import (
    build_simris_published_network,
    evaluate_simris_channel_published_case,
    get_simris_published_geometry,
    SimRISChannel,
    SimRISConfig,
    SimRISLoSConfig,
    SimRISStochasticChannel,
    SimRISValidationResult,
    evaluate_simris_from_nodes,
    evaluate_simris_los_published_case,
    evaluate_simris_los_from_nodes,
    evaluate_simris_los_reference,
    evaluate_simris_stochastic_channel_published_case,
    simulate_simris_published_case,
    simulate_simris_channels,
    summarize_simris_tensors,
    validate_simris_configuration,
)

__all__ = [
    "ChannelEvaluation",
    "ChannelModel",
    "DEFAULT_RIS_LINK_CONFIG",
    "LinkBudgetChannel",
    "build_link_budget_config",
    "build_link_budget_config_from_nodes",
    "evaluate_ris_link_from_nodes",
    "evaluate_ris_link_metrics",
    "build_simris_published_network",
    "evaluate_simris_channel_published_case",
    "get_simris_published_geometry",
    "SimRISChannel",
    "SimRISConfig",
    "SimRISLoSConfig",
    "SimRISStochasticChannel",
    "SimRISValidationResult",
    "evaluate_simris_from_nodes",
    "evaluate_simris_los_published_case",
    "evaluate_simris_los_from_nodes",
    "evaluate_simris_los_reference",
    "evaluate_simris_stochastic_channel_published_case",
    "simulate_simris_published_case",
    "simulate_simris_channels",
    "summarize_simris_tensors",
    "validate_simris_configuration",
]
